# Generated by Django 4.0.6 on 2022-07-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='kdrama',
            name='awards',
            field=models.ManyToManyField(to='main_app.award'),
        ),
    ]
