# Generated by Django 4.0.6 on 2022-07-17 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_kdrama_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Watch Part Date')),
                ('stars', models.CharField(choices=[('5', 'Five Stars'), ('4', 'Four Stars'), ('3', 'Three Stars'), ('2', 'Two Stars'), ('1', 'One Stars')], default='5', max_length=1)),
                ('episodes', models.PositiveSmallIntegerField()),
                ('kdrama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.kdrama')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
