# Generated by Django 4.0.6 on 2022-07-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_watching_date_alter_watching_episodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watching',
            name='date',
            field=models.DateTimeField(verbose_name='Watch Date'),
        ),
    ]
