# Generated by Django 4.0.6 on 2022-07-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_kdrama_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watching',
            name='stars',
            field=models.CharField(choices=[('5', '✯✯✯✯✯'), ('4', '✯✯✯✯'), ('3', '✯✯✯'), ('2', '✯✯'), ('1', '✯')], default='5', max_length=1),
        ),
    ]
